-- ===============================
-- USERS
-- ===============================
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(512) NOT NULL,
    CONSTRAINT uq_user_email UNIQUE (email)
);

-- ===============================
-- ITEMS
-- ===============================
CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    available BOOLEAN NOT NULL,
    owner_id BIGINT NOT NULL,
    CONSTRAINT fk_item_owner FOREIGN KEY (owner_id)
        REFERENCES users (id) ON DELETE CASCADE
);

-- ===============================
-- BOOKINGS
-- ===============================
CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_date   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    item_id BIGINT NOT NULL,
    booker_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,

    CONSTRAINT fk_booking_item FOREIGN KEY (item_id)
        REFERENCES items (id) ON DELETE CASCADE,

    CONSTRAINT fk_booking_booker FOREIGN KEY (booker_id)
        REFERENCES users (id) ON DELETE CASCADE
);

-- Индекс для ускорения поиска бронирований
CREATE INDEX IF NOT EXISTS idx_bookings_item_id ON bookings(item_id);
CREATE INDEX IF NOT EXISTS idx_bookings_booker_id ON bookings(booker_id);

-- ===============================
-- COMMENTS
-- ===============================
CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text TEXT NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    item_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,

    CONSTRAINT fk_comment_item FOREIGN KEY (item_id)
        REFERENCES items (id) ON DELETE CASCADE,

    CONSTRAINT fk_comment_author FOREIGN KEY (author_id)
        REFERENCES users (id) ON DELETE CASCADE
);

-- Индекс для ускорения вывода комментариев к вещам
CREATE INDEX IF NOT EXISTS idx_comments_item_id ON comments(item_id);
